name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Show Forge version
        run: |
          cd backend
          forge --version

      - name: Run Forge fmt
        run: |
          cd backend
          forge fmt --check

      - name: Run Forge build
        run: |
          cd backend
          forge build --sizes

      - name: Run Forge tests
        run: |
          cd backend
          forge test -vvv
